### ISSUE TITLE
Enable split yaml enabling the include command

### ISSUE THREAD

**Issue by rodrigopex** [zeta-middleware/zeta#109]
It would be good to enable separation of the system's definitions. If the project grows in size it will be difficult to track the characteristics. If you imagine a project with 100 channels and 8 services and in a future 40 message formats it will be no comfortable maintain the YAML file. 

### Proposal
It would be possible to separate the descriptions and put them in a separated directory (zt for example). 
```yaml
Config:
    storage_partition: 'partition3'

Channels:
    - FIRMWARE_VERSION:
        initial_value: [0, 5, 0]
        read_only: True
    !include "./zt/channels.yaml"

!include "./zt/services.yaml"

!include "./zt/message_formats.yaml"
```
