### ISSUE TITLE
Make Zeta service-centered

### ISSUE THREAD

**Issue by rodrigopex** [zeta-middleware/zeta#34]
### Current

```yaml
Config:
  nvs_sector_size: 'DT_FLASH_ERASE_BLOCK_SIZE'
  nvs_sector_count: 4
  nvs_storage_offset: 'DT_FLASH_AREA_STORAGE_OFFSET'

Services:
  - CORE: 
      priority: 5
      stack_size: 512
  - HAL: 
      priority: 2
      stack_size: 1024
  - APP: 
      priority: 1
      stack_size: 2048
      
Channels:
  - FIRMWARE_VERSION:
      size: 4
      set: 'NULL'
      initial_value: [0xF1, 0xF2, 0xF3, 0xF4]
      
  - POWER_VAL:
      size: 2
      persistent: True
      validate: 'zeta_validator_different_of_zero'
      subscribers:
        - !ref APP
      publishers:
        - !ref CORE
        
  - SENSOR_VAL:
      size: 1
      subscribers:
        - !ref CORE
      publishers:
        - !ref HAL

```

### Proposal

```yaml
Config:
  nvs_sector_size: 'DT_FLASH_ERASE_BLOCK_SIZE'
  nvs_sector_count: 4
  nvs_storage_offset: 'DT_FLASH_AREA_STORAGE_OFFSET'
    
Channels:
  - FIRMWARE_VERSION:
      size: 4
      set: 'NULL'
      initial_value: [0xF1, 0xF2, 0xF3, 0xF4]
      
  - POWER_VAL:
      size: 2
      persistent: True
      validate: 'zeta_validator_different_of_zero'
        
  - SENSOR_VAL:
      size: 1

Services:
  - CORE: 
      priority: 5
      stack_size: 512
      sub_channels:
         - !ref SENSOR_VAL
      pub_channels:
         - !ref POWER_VAL

  - HAL: 
      priority: 2
      stack_size: 1024
      pub_channels:
         - !ref SENSOR_VAL

  - APP: 
      priority: 1
      stack_size: 2048
      sub_channels:
         - !ref POWER_VAL
      pub_channels:
```
