### ISSUE TITLE
Add a field callback_behavior to YAML

### ISSUE THREAD

**Issue by lucaspeixotot** [zeta-middleware/zeta#63]
Today the Zeta system is calling the service callback only when the data received is different than the existent. It is necessary to create a way for the user to define whether the channel will call service callback on update or on change.

The idea is to create a field in YAML file like this:

```
  - NET_RESPONSE:
      size: 5
      callback_behavior: on_update
  - NET_RESPONSE:
      size: 5
      callback_behavior: on_change
```

And to create the infrastructure to it works on Zeta system. The suggestion is that the default mode can be `on_update`.
