### ISSUE TITLE
Add message format fields to the yaml

### ISSUE THREAD

**Issue by rodrigopex** [zeta-middleware/zeta#98]
It enables the developer to define the data format of a channel. 

### Proposal
```yaml
Channels:
    - COMPLEX_REQUEST:
        message: !ref REQ
    - COMPLEX_RESPONSE:
        message: !ref RESP

Services:
    - CORE:
        stack_size: 4096
        priority: 2
        pub_channels:
            - !ref COMPLEX_RESPONSE
        sub_channels:
            - !ref COMPLEX_REQUEST
    - NET:
        stack_size: 512
        priority: 4
        pub_channels:
            - !ref COMPLEX_REQUEST
        sub_channels:
            - !ref COMPLEX_RESPONSE

Messages:
    - REQ: 
        mtype: struct
        fields:
        - id: u8
        - flag:
            type: bitarray_u8
            fields:
            - read: 
              mtype: bits
              size: 1
            - write:
              mtype: bits
              size: 1
            - erase: 
              mtype: bits
              size: 1
            - update: 
              mtype: bits
              size: 1
        - data: 
           mtype: u8
           size: 32
    - RESP: 
        type: struct
        fields:
        - id: u8
        - kind:
            type: bitarray_u8
            fields:
            - ok: 
              mtype: bits
              size: 1
            - fail: 
              mtype: bits
              size: 1
        - data:
           mtype: u32
           size: 5

```

### Code generated inside zeta.h
```c
//... Rest of code
#define ZT_DATA_REQ(data)                \
    (zt_data_t *) (zt_data_req_t[])      \
    {                                    \
        {                                \
            sizeof(struct req), {data}     \
        }                                \
    }

#define ZT_DATA_RESP(data)               \
    (zt_data_t *) (zt_data_resp_t[])     \
    {                                    \
        {                                \
            sizeof(struct resp), {data}    \
        }                                \
    }

struct req {
    u8_t id;
    struct {
        u8_t read: 1;
        u8_t write: 1;
        u8_t erase: 1;
        u8_t update: 1;
    } flag;
    u8_t data[32];
}; 

struct resp {
        u8_t id;
        struct {
            u8_t ok: 1;
            u8_t fail: 1;
        } kind;
        u32_t data[5];
}; 


typedef struct {
    size_t size;
    struct req value; 
} zt_data_req_t;

typedef struct {
    size_t size;
    struct resp value; 
} zt_data_resp_t;

union data {
    zt_data_s8_t s8;
    zt_data_u8_t u8;
    zt_data_s16_t s16;
    zt_data_u16_t u16;
    zt_data_s32_t s32;
    zt_data_u32_t u32;
    zt_data_s64_t s64;
    zt_data_u64_t u64;
    zt_data_req_t req;     \\ <-- Here!
    zt_data_resp_t resp;   \\ <-- Here!
    zt_data_bytes_t bytes;
};

```
### Using this

```c
// publishing
zt_data_t* request = ZT_DATA_REQ(.id = 50, .data = {0}, .flag={0});
request->req.id++;
request->req.flag.erase = 1;
zt_chan_pub(ZT_COMPLEX_REQUEST_CHANNEL, request);

// reading
zt_data_t* response = ZT_DATA_RESP(0);
zt_chan_read(ZT_COMPLEX_REQUEST_CHANNEL, response);
response->size; // this filed was added
response->resp.id;
response->resp.data[0];
response->resp.ok;
response->resp.fail;

```
[1] - https://www.asyncapi.com/
